# This is a basic workflow to help you get started with Actions

name: Release RPi Control-Board v2 Firmware

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Framework
        uses: actions/checkout@v2
        with:
          repository: smuuze/rpi_control_frmwrk
          path: rpi_control_frmwrk
          
      - name: Checkout Firmware
        uses: actions/checkout@v2
        with:
          repository: smuuze/rpi_control_fw
          path: rpi_control_fw

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo --- Content of rpi_control_frmwrk ---
          ls rpi_control_frmwrk
          echo --- Content of rpi_control_fw ---
          ls rpi_control_fw
          cd rpi_control_fw/cfg_rpi_hat_control_board_v2
          echo --- Content of rpi_control_fw/cfg_rpi_hat_control_board_v2 ---
          ls
          
      - name: Build RPi Control-Board v2
        uses: bazhenov/action-avr-make@v1.0
